language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install:
  - npm install
  - grunt test
  - grunt dist
  - grunt codedeploy
deploy:
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: LZToB5h0IoW4K21i2gYT4cdiWjzlb8rnz7pL8gL/y/gRX9UjWr2xHDtNgBbAi8nQcle0/z4NgwG2UzfaP4EmKN09P9WFyUtmIOtwO8cPMqg0L/W8pP6gWe/Ebfd42AILJ/niuklP79Hb9m71pNJfm+XhFbWXCEDAo3DYFa1uYEE=
    skip_cleanup: true
    bucket: hmda-edit-check-api
    local_dir: dist
    upload-dir: develop
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: LZToB5h0IoW4K21i2gYT4cdiWjzlb8rnz7pL8gL/y/gRX9UjWr2xHDtNgBbAi8nQcle0/z4NgwG2UzfaP4EmKN09P9WFyUtmIOtwO8cPMqg0L/W8pP6gWe/Ebfd42AILJ/niuklP79Hb9m71pNJfm+XhFbWXCEDAo3DYFa1uYEE=
    bucket: hmda-edit-check-api
    key: develop/hmda-edit-check-api.zip
    application: hmda-edit-check-api
    deployment_group: hmda-pilot-dev
    on:
      all_branches: true
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: LZToB5h0IoW4K21i2gYT4cdiWjzlb8rnz7pL8gL/y/gRX9UjWr2xHDtNgBbAi8nQcle0/z4NgwG2UzfaP4EmKN09P9WFyUtmIOtwO8cPMqg0L/W8pP6gWe/Ebfd42AILJ/niuklP79Hb9m71pNJfm+XhFbWXCEDAo3DYFa1uYEE=
    skip_cleanup: true
    bucket: hmda-edit-check-api
    local_dir: dist
    upload-dir: master
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: LZToB5h0IoW4K21i2gYT4cdiWjzlb8rnz7pL8gL/y/gRX9UjWr2xHDtNgBbAi8nQcle0/z4NgwG2UzfaP4EmKN09P9WFyUtmIOtwO8cPMqg0L/W8pP6gWe/Ebfd42AILJ/niuklP79Hb9m71pNJfm+XhFbWXCEDAo3DYFa1uYEE=
    bucket: hmda-edit-check-api
    key: master/hmda-edit-check-api-codedeploy.zip
    application: hmda-edit-check-api
    deployment_group: hmda-pilot-prod
    on:
      branch: master
