language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install:
- npm install
- grunt test
- grunt dist
- grunt codedeploy
deploy:
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    skip_cleanup: true
    bucket: hmda-edit-check-api
    local_dir: dist
    upload-dir: develop
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    bucket: hmda-edit-check-api
    key: develop/hmda-edit-check-api.zip
    application: hmda-edit-check-api
    deployment_group: hmda-pilot-dev
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    skip_cleanup: true
    bucket: hmda-edit-check-api
    local_dir: dist
    upload-dir: master
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    bucket: hmda-edit-check-api
    key: master/hmda-edit-check-api-codedeploy.zip
    application: hmda-edit-check-api
    deployment_group: hmda-pilot-prod
    on:
      branch: master
