language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install:
- npm install
before_deploy:
- grunt dist
- grunt codedeploy
deploy:
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
  skip_cleanup: true
  bucket: hmda-edit-check-api
  local_dir: dist
  upload-dir: develop
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
  bucket: hmda-edit-check-api
  key: develop/hmda-edit-check-api-codedeploy.zip
  application: hmda-edit-check-api
  deployment_group: hmda-edit-check-api-dev
  on:
    all_branches: true
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
  skip_cleanup: true
  bucket: hmda-edit-check-api
  local_dir: dist
  upload-dir: master
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
  bucket: hmda-edit-check-api
  key: master/hmda-edit-check-api-codedeploy.zip
  application: hmda-edit-check-api
  deployment_group: hmda-edit-check-api-dev
  on:
    branch: master
notifications:
  hipchat:
    rooms:
      secure: T0cvwtL8w6ZaRbYl80IN4I1a5AtKauhwuSPTWEoPNZhcWnG1DYLH0Txjg5x9iTbncctx0QoeQad5EYrfoCCqkSarGJR/j9u29Lnla647BCjTSnpbMjVe3vqw+brNF0Vw68W6eTwBhiCUagwZWJxCLpMnTx9MVD/JuR6VWHqLSQI=
